name: MegaMekLab Nightly CI

on:
  schedule:
    - cron: "0 3 * * *"

env:
  GRADLE_OPTS: "-Dscan.link.VCS=https://github.com/MegaMek/megameklab/commit/${{ github.sha }}"

jobs:
  nightly_ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java-distribution: [temurin]
        java-version: [17]
      fail-fast: false

    name: Nightly MegaMekLab CI ${{ matrix.os }} on ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: megameklab

      - name: Checkout MegaMek
        uses: actions/checkout@v4
        with:
          repository: MegaMek/megamek
          path: megamek

      - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Add MMLRevision file
        run: |
          echo ${{ github.sha }} >> megameklab/megameklab/mml-revision.txt

      - name: Build with Gradle
        working-directory: megameklab
        run: ./gradlew clean build --stacktrace --scan

      - name: Upload Test Logs on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.java-distribution }}-jdk${{ matrix.java-version }}-ci-failure-logs
          path: megameklab/megameklab/build/reports/

      #      - name: Upload Zip Release
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: mml-release-zip-${{ matrix.java-distribution }}-jdk${{ matrix.java-version }}
      #          path: ./megameklab/megameklab/build/distributions/*.zip

      - name: Upload TarGZ Release
        uses: actions/upload-artifact@v4
        with:
          name: mml-release-tgz-${{ matrix.java-distribution }}-jdk${{ matrix.java-version }}
          path: ./megameklab/megameklab/build/distributions/*.tar.gz
